### ISSUE TITLE
pyCPA port: core.combine_rows

### ISSUE THREAD

**Issue by mikapfl** [pik-primap/primap2#3]
Port the functionality of pyCPA's [core.combine_rows](https://github.com/JGuetschow/pyCPA/blob/master/src/pyCPA/core/core.py#L372).

**Comment by mikapfl** [comment]
`combine_rows` functionality:
1. Restrict the data by indexing on specified dimensions (defined
   in `other_cols`).
2. Along a specified dimension either of (defined in `mapping`):
   - `x = sum(a, b, c, d)`
   - `x = a - sum(b, c, d)`
   - `x = a`
   - `x = -a`
3. Multiple dimensions can be specified in the `mapping`, the actions will
   be applied simultaneously. With the given operators, this is
   mathematically equivalent to applying them serially.
4. Metadata dimensions are dropped (defined in `cols_to_remove`).

**Comment by mikapfl** [comment]
If `x` is a new value for the dimension, in xarray we need to reindex to insert it. Maybe we want a function where the caller doesn't have to care if a particular value along a dimension already exists or not, I think then all the functionality can be reached by a few chained standard xarray calls.

**Comment by JGuetschow** [comment]
comments on `combine rows` functionality:
1. yes
2. all combinations of + and - are possible (e.g. `x = - sum(a,b,c)`).
3. yes
4. yes, but maybe that's not necessary because the metadata is stored in a different way in primap2

And regarding the next comment: I think it would be good if one does not have to know if a value already exists. 

For the data we need user definable rules on what to do in that case (keep old, overwrite, ...)
